In [1]:
import logging
logging.basicConfig(level=logging.DEBUG)


from Model import *
from dataset import Dataset
import numpy as np
from Optimizer import Optimizer
from Loss import *
from Layer import backproplogger

backproplogger.setLevel(logging.WARNING)

# logger = logging.getLogger('simple_example')
# logger.setLevel(logging.DEBUG)

In [2]:
def count_errors(yhati, yi):
    errcount = 0
    for yhat, y in zip(yhati, yi):
        if (np.argmax(yhat) != np.argmax(y)):
            errcount += 1
    return(errcount)

In [9]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 20, 20, 10, 4], activations = ["sigmoid", "sigmoid", "sigmoid", "softmax"], optimizer=Optimizer(learning_rate=0.1, Loss=CrossEntropyLoss()))
test = np.genfromtxt("../data/trainout.csv", delimiter=",")
l = m.layers[-1]
d.x = d.x
d.y = d.y
d.y[0][2] = 0
d.y[0][0] = 1
mask = []
for i in range(1600):
    mask.append(i)
ex = d.x[mask]
ey = d.y[mask]

In [10]:
from Loss import losslogger
from Layer import backproplogger
backproplogger.setLevel(logging.WARN)
losslogger.setLevel(logging.WARN)
x = ex
y = ey
for i in range(1000):
    # logging.debug(f"\n\n{i}\n\n")
    m.fit(x, y)
    # print("\n")
print(f"l.z:\n{l.z}\n\nl.a:\n{l.a}\n\ny:\n{y}\n\nx:\n{x}\n\nl.w:\n{l.w}\n\n")
print(count_errors(l.a, y))

l.z:
[[-1.20 -0.37  2.99 -1.29]
 [-0.08  0.26 -2.28  2.70]
 [-1.53 -0.15  3.37 -1.51]
 ...
 [ 2.94 -2.30 -0.90 -0.03]
 [-2.30  3.64 -1.08  0.58]
 [-2.24  3.57 -0.79  0.23]]

l.a:
[[ 0.01  0.03  0.94  0.01]
 [ 0.05  0.08  0.01  0.86]
 [ 0.01  0.03  0.96  0.01]
 ...
 [ 0.93  0.00  0.02  0.05]
 [ 0.00  0.94  0.01  0.04]
 [ 0.00  0.95  0.01  0.03]]

y:
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]

x:
[[ 1.00 -1.03  0.88 ...  1.04  0.36  0.21]
 [ 1.00 -1.16 -1.39 ... -0.54 -1.21  0.65]
 [ 1.00 -0.80  1.26 ...  1.86  1.02  1.32]
 ...
 [ 1.00  0.97 -0.85 ... -0.32  1.33 -1.75]
 [ 1.00  0.79  0.44 ... -1.25 -1.06  1.32]
 [ 1.00  1.25  0.82 ... -0.01 -1.48  0.10]]

l.w:
[[-0.22 -0.40 -0.02  0.44]
 [-1.12  0.65  1.75 -1.36]
 [ 1.76 -1.46 -0.88  0.56]
 [ 0.87  0.30 -1.83  0.86]
 [ 0.14 -0.70  1.29 -0.75]
 [ 1.68 -1.69 -0.08 -0.52]
 [-1.16  1.75 -1.14  0.72]
 [-0.21  0.34  1.10 -1.20]
 [-0.95 -0.28  0.91  0.88]
 [ 0.27  1.64 -0.78 -0.85]
 [-0.99  0.87 -0.73  1.18]]


31


In [5]:
c = 0
i = 0
for x, y in zip(m.feed_forward(d.x), d.y):
    if (np.argmax(x) != np.argmax(y)):
        print(x, y)
        c += 1
print(c)

.20] [0 0 0 1]
[ 0.38  0.21  0.20  0.21] [0 0 1 0]
[ 0.32  0.27  0.18  0.23] [0 1 0 0]
[ 0.38  0.21  0.20  0.21] [0 0 1 0]
[ 0.38  0.21  0.19  0.22] [0 0 1 0]
[ 0.33  0.26  0.19  0.22] [0 1 0 0]
[ 0.41  0.22  0.18  0.20] [0 0 0 1]
[ 0.37  0.23  0.19  0.20] [0 0 0 1]
[ 0.34  0.26  0.18  0.23] [0 1 0 0]
[ 0.38  0.21  0.19  0.21] [0 0 1 0]
[ 0.44  0.20  0.16  0.20] [0 0 0 1]
[ 0.33  0.27  0.18  0.22] [0 1 0 0]
[ 0.32  0.27  0.17  0.24] [0 1 0 0]
[ 0.37  0.22  0.19  0.22] [0 0 1 0]
[ 0.38  0.21  0.19  0.21] [0 0 1 0]
[ 0.40  0.22  0.18  0.20] [0 1 0 0]
[ 0.38  0.22  0.18  0.22] [0 0 1 0]
[ 0.34  0.26  0.17  0.23] [0 1 0 0]
[ 0.31  0.28  0.18  0.23] [0 1 0 0]
[ 0.32  0.27  0.19  0.23] [0 1 0 0]
[ 0.33  0.26  0.18  0.23] [0 1 0 0]
[ 0.33  0.26  0.17  0.23] [0 1 0 0]
[ 0.43  0.20  0.17  0.20] [0 0 0 1]
[ 0.33  0.26  0.19  0.22] [0 1 0 0]
[ 0.31  0.27  0.18  0.23] [0 1 0 0]
[ 0.39  0.22  0.18  0.20] [0 0 0 1]
[ 0.28  0.29  0.17  0.25] [1 0 0 0]
[ 0.33  0.26  0.18  0.23] [0 1 0 0]
[ 0.34  0.25 

In [35]:
m.feed_forward(d.x)

array([[ 1.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  1.00],
       [ 0.00,  0.00,  1.00,  0.00],
       ...,
       [ 1.00,  0.00,  0.00,  0.00],
       [ 0.00,  1.00,  0.00,  0.00],
       [ 0.00,  1.00,  0.00,  0.00]])

In [40]:
for x in m.feed_forward(d.x):
    print(np.argmax(x))

0
3
2
0
0
3
0
1
0
1
1
1
1
3
2
2
0
0
2
1
0
0
2
1
0
1
3
1
0
1
1
0
2
1
0
0
1
1
3
1
0
1
0
1
1
0
0
1
3
0
0
3
3
0
0
3
1
3
1
0
3
2
1
1
1
1
1
0
0
1
2
3
3
1
2
1
0
0
1
1
1
3
3
0
1
1
1
1
1
0
0
0
0
1
1
1
0
2
3
1
0
1
0
1
0
0
3
0
1
3
3
2
0
0
0
0
0
3
1
1
0
3
0
1
1
3
1
3
0
1
3
0
3
1
2
0
0
0
1
0
0
0
0
1
0
0
3
0
0
0
0
0
0
3
3
1
0
1
2
0
1
1
1
3
0
1
1
1
3
0
2
0
0
2
1
0
0
1
0
0
3
1
0
3
3
1
1
3
1
0
3
1
0
1
3
1
1
0
0
3
1
0
0
0
0
1
0
1
1
0
1
0
3
3
2
1
0
2
0
0
1
1
0
3
0
2
1
0
1
1
1
0
1
2
1
1
3
0
1
1
1
0
1
1
1
1
0
1
0
0
0
3
3
0
1
2
2
3
0
2
3
1
0
0
3
3
3
0
1
0
0
0
1
1
0
0
2
1
1
0
1
2
1
1
0
0
0
1
1
0
0
1
1
1
0
0
1
0
0
1
0
1
3
1
1
0
3
0
1
3
2
1
3
1
0
0
0
3
3
1
1
3
3
0
1
0
0
0
0
0
3
1
1
1
0
0
3
0
0
1
3
0
0
1
3
0
3
0
1
1
0
0
0
0
1
0
3
1
0
0
1
1
0
0
3
2
3
1
0
1
0
1
1
1
1
2
0
1
3
0
1
0
3
1
0
1
0
1
0
1
1
3
1
1
0
2
0
3
0
0
0
1
3
1
2
1
0
0
3
0
3
0
0
0
1
0
3
1
3
1
1
3
1
1
3
0
1
1
1
0
0
0
1
0
1
1
0
0
3
0
1
2
2
0
0
1
1
0
0
0
1
1
3
1
3
3
2
0
1
0
1
0
0
0
1
0
0
1
3
0
0
0
1
1
1
0
1
1
0
2
1
1
0
3
1
1
0
0
1
1
0
1
3
3
1
1
3
0
0
2


In [10]:
m.feed_forward(d.x)
djda = m.Optimizer.Loss.loss_derivative(m.layers[-1].a, d.y)

DEBUG:root:y:
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]
DEBUG:root:yhat:
[[ 0.09  0.57  0.22  0.12]
 [ 0.02  0.35  0.50  0.13]
 [ 0.06  0.67  0.14  0.14]
 ...
 [ 0.27  0.21  0.38  0.15]
 [ 0.29  0.31  0.15  0.25]
 [ 0.39  0.23  0.10  0.29]]
DEBUG:root:-y / yhat:
[[ 0.00  0.00 -4.59  0.00]
 [ 0.00  0.00  0.00 -7.53]
 [ 0.00  0.00 -7.34  0.00]
 ...
 [-3.74  0.00  0.00  0.00]
 [ 0.00 -3.19  0.00  0.00]
 [ 0.00 -4.33  0.00  0.00]]


In [11]:
l = m.layers[-1]
dadz = l.activation_derivative(l.z, l.a)
# print(f"{dadz.shape = }, {djda.shape = }")
# logging.debug(f"djda:\n {djda}\n")
djdz = np.einsum( 'ik,ikj->ij', djda, dadz)
djdz2 = l.a - d.y


array([[ 0.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00],
       ...,
       [ 0.00,  0.00,  0.00,  0.00],
       [ 0.00, -0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00]])

In [10]:
print(l.a)
print(d.y)
-1 / 0.22

[[ 0.09  0.57  0.22  0.12]
 [ 0.02  0.35  0.50  0.13]
 [ 0.06  0.67  0.14  0.14]
 ...
 [ 0.27  0.21  0.38  0.15]
 [ 0.29  0.31  0.15  0.25]
 [ 0.39  0.23  0.10  0.29]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]


-4.545454545454546