In [1]:
import logging
logging.basicConfig(level=logging.DEBUG)

from Model import *
from dataset import Dataset
import numpy as np
from Optimizer import Optimizer
from Loss import *
from Layer import backproplogger
backproplogger.setLevel(logging.WARNING)

# logger = logging.getLogger('simple_example')
# logger.setLevel(logging.DEBUG)

In [2]:
def count_errors(yhati, yi):
    errcount = 0
    for yhat, y in zip(yhati, yi):
        if (np.argmax(yhat) != np.argmax(y)):
            errcount += 1
    return(errcount)

In [11]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 20, 20, 10, 4], activations = ["sigmoid", "sigmoid", "sigmoid", "softmax"], optimizer=Optimizer(learning_rate=0.1, Loss=CrossEntropyLoss()))
test = np.genfromtxt("../data/trainout.csv", delimiter=",")
l = m.layers[-1]
d.x = d.x
d.y = d.y
d.y[0][2] = 0
d.y[0][0] = 1
mask = []
for i in range(1600):
    mask.append(i)
ex = d.x[mask]
ey = d.y[mask]

In [16]:
from Loss import losslogger
from Layer import backproplogger
backproplogger.setLevel(logging.WARN)
losslogger.setLevel(logging.WARN)
x = ex
y = ey
for i in range(1000):
    # logging.debug(f"\n\n{i}\n\n")
    m.fit(x, y)
    # print("\n")
print(f"l.z:\n{l.z}\n\nl.a:\n{l.a}\n\ny:\n{y}\n\nx:\n{x}\n\nl.w:\n{l.w}\n\n")
print(count_errors(l.a, y))

l.z:
[[-0.01 -6.01  4.49  1.25]
 [-2.89 -0.03 -0.19  3.79]
 [ 0.09 -6.41  4.87  1.12]
 ...
 [ 4.09 -1.09 -1.29 -2.04]
 [ 0.08  5.05 -5.17  0.91]
 [ 0.45  4.98 -5.21  0.57]]

l.a:
[[ 0.01  0.00  0.95  0.04]
 [ 0.00  0.02  0.02  0.96]
 [ 0.01  0.00  0.97  0.02]
 ...
 [ 0.99  0.01  0.00  0.00]
 [ 0.01  0.98  0.00  0.02]
 [ 0.01  0.98  0.00  0.01]]

y:
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]

x:
[[ 1.00 -1.03  0.88 ...  1.04  0.36  0.21]
 [ 1.00 -1.16 -1.39 ... -0.54 -1.21  0.65]
 [ 1.00 -0.80  1.26 ...  1.86  1.02  1.32]
 ...
 [ 1.00  0.97 -0.85 ... -0.32  1.33 -1.75]
 [ 1.00  0.79  0.44 ... -1.25 -1.06  1.32]
 [ 1.00  1.25  0.82 ... -0.01 -1.48  0.10]]

l.w:
[[ 0.05 -0.30 -0.23  0.28]
 [-1.09 -1.08  1.38  0.70]
 [ 2.02 -2.30  0.90 -0.63]
 [ 1.77  2.82 -2.51 -1.88]
 [-0.50 -1.61  2.48 -0.39]
 [ 1.55 -1.47  0.21 -0.90]
 [-0.81  0.27 -0.54  1.25]
 [-0.61 -1.10  1.15  0.59]
 [-1.49  0.20  0.35  1.50]
 [ 0.30  1.53 -1.16 -0.39]
 [-0.71  1.97 -2.01  1.09]]


30


In [19]:
m.layers[0].w - qw

array([[-0.04, -0.03,  0.07,  0.15,  0.16, -0.05,  0.00, -0.03, -0.02,
         0.01, -0.09,  0.14,  0.01, -0.11,  0.12, -0.05,  0.04, -0.03,
         0.12, -0.03],
       [-0.05, -0.03,  0.08,  0.16,  0.16, -0.05, -0.00, -0.03, -0.02,
         0.02, -0.08,  0.15,  0.01, -0.11,  0.12, -0.06,  0.04, -0.03,
         0.11, -0.03],
       [ 0.15, -0.24,  0.14, -0.03,  0.06, -0.30, -0.06, -0.03,  0.13,
        -0.19, -0.45,  0.45,  0.13, -0.32,  0.22, -0.07,  0.20, -0.10,
         0.43, -0.41],
       [-0.18,  0.13,  0.03,  0.12,  0.10,  0.07,  0.16, -0.12,  0.10,
        -0.15, -0.24,  0.20, -0.08, -0.27, -0.10,  0.01, -0.15, -0.17,
         0.23, -0.16],
       [-0.15,  0.27, -0.11,  0.02, -0.08,  0.30,  0.05,  0.04, -0.15,
         0.21,  0.50, -0.49, -0.13,  0.37, -0.23,  0.04, -0.21,  0.12,
        -0.48,  0.46],
       [ 0.27, -0.12,  0.72, -0.47, -0.37, -0.25, -0.42,  0.50, -0.14,
        -0.01, -0.44,  0.40,  0.10, -0.28, -0.00, -0.59, -0.01,  0.07,
         0.38, -0.33],
       [ 0

In [18]:

qw = [[-0.25,  0.17, -0.14,  0.04, -0.34,  0.29,  0.28, -0.33,  0.32,
        -0.26, -0.17,  0.09,  0.31,  0.22, -0.35,  0.01,  0.03, -0.01,
         0.20, -0.22],
       [ 0.19, -0.34, -0.24, -0.26, -0.13,  0.12, -0.02,  0.22, -0.15,
         0.16,  0.12, -0.11, -0.12,  0.31,  0.09,  0.32,  0.18,  0.23,
        -0.05, -0.01],
       [-0.03,  0.27, -0.27,  0.37, -0.03, -0.11, -0.02, -0.22,  0.02,
        -0.40, -0.46,  0.31,  0.09, -0.44, -0.04, -0.18, -0.27, -0.02,
         0.09, -0.47],
       [-0.03,  0.29, -0.31, -0.14,  0.12,  0.07,  0.10, -0.07,  0.31,
         0.09,  0.18, -0.18, -0.07,  0.32, -0.29,  0.28, -0.38,  0.06,
        -0.40,  0.21],
       [ 0.06,  0.33,  0.35, -0.08,  0.10,  0.36,  0.08,  0.01, -0.18,
        -0.08,  0.49, -0.22,  0.32,  0.35,  0.03, -0.37,  0.24,  0.33,
        -0.50,  0.25],
       [-0.09,  0.07,  0.08,  0.03, -0.14, -0.29,  0.22,  0.27, -0.20,
        -0.21, -0.08, -0.11,  0.25, -0.19, -0.08,  0.07, -0.02, -0.12,
         0.18, -0.22],
       [-0.26,  0.02,  0.25, -0.25, -0.31,  0.38, -0.26,  0.20, -0.18,
         0.16,  0.30, -0.50, -0.11,  0.01, -0.36, -0.40, -0.42,  0.11,
        -0.46,  0.06],
       [ 0.36,  0.27,  0.38, -0.36, -0.19, -0.18, -0.10,  0.18, -0.11,
         0.22,  0.18,  0.03, -0.22,  0.26,  0.05, -0.19, -0.10,  0.39,
        -0.21,  0.01],
       [-0.01,  0.17, -0.39,  0.11,  0.23,  0.39,  0.25, -0.30, -0.16,
        -0.03,  0.21, -0.41, -0.13, -0.09,  0.25,  0.33,  0.11,  0.00,
        -0.31,  0.39]]
c = 0
i = 0
for x, y in zip(m.feed_forward(d.x), d.y):
    if (np.argmax(x) != np.argmax(y)):
        print(x, y)
        c += 1
print(c)

[ 0.01  0.00  0.95  0.04] [1 0 0 0]
[ 0.00  0.03  0.01  0.95] [0 0 1 0]
[ 0.01  0.98  0.00  0.01] [0 0 1 0]
[ 0.01  0.00  0.96  0.03] [0 0 0 1]
[ 0.01  0.98  0.00  0.01] [0 0 1 0]
[ 0.01  0.98  0.00  0.02] [0 0 1 0]
[ 0.01  0.00  0.97  0.02] [0 0 0 1]
[ 0.99  0.01  0.00  0.00] [0 0 1 0]
[ 0.01  0.00  0.95  0.03] [1 0 0 0]
[ 0.01  0.00  0.92  0.07] [1 0 0 0]
[ 0.00  0.01  0.04  0.94] [0 0 1 0]
[ 0.02  0.00  0.97  0.02] [1 0 0 0]
[ 0.01  0.00  0.97  0.02] [0 1 0 0]
[ 0.07  0.92  0.00  0.01] [1 0 0 0]
[ 0.02  0.97  0.00  0.01] [0 0 0 1]
[ 0.02  0.97  0.00  0.01] [1 0 0 0]
[ 0.00  0.02  0.02  0.96] [0 1 0 0]
[ 0.01  0.97  0.00  0.02] [0 0 0 1]
[ 0.99  0.01  0.00  0.00] [0 0 1 0]
[ 0.99  0.01  0.00  0.00] [0 1 0 0]
[ 0.99  0.01  0.00  0.00] [0 1 0 0]
[ 0.01  0.00  0.98  0.01] [0 0 0 1]
[ 0.01  0.00  0.96  0.03] [0 0 0 1]
[ 0.02  0.97  0.00  0.01] [0 0 1 0]
[ 0.01  0.00  0.98  0.01] [0 0 0 1]
[ 0.01  0.96  0.00  0.03] [1 0 0 0]
[ 0.01  0.00  0.97  0.02] [1 0 0 0]
[ 0.01  0.00  0.97  0.02] [1

In [35]:
m.feed_forward(d.x)

array([[ 1.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  1.00],
       [ 0.00,  0.00,  1.00,  0.00],
       ...,
       [ 1.00,  0.00,  0.00,  0.00],
       [ 0.00,  1.00,  0.00,  0.00],
       [ 0.00,  1.00,  0.00,  0.00]])

In [40]:
for x in m.feed_forward(d.x):
    print(np.argmax(x))

0
3
2
0
0
3
0
1
0
1
1
1
1
3
2
2
0
0
2
1
0
0
2
1
0
1
3
1
0
1
1
0
2
1
0
0
1
1
3
1
0
1
0
1
1
0
0
1
3
0
0
3
3
0
0
3
1
3
1
0
3
2
1
1
1
1
1
0
0
1
2
3
3
1
2
1
0
0
1
1
1
3
3
0
1
1
1
1
1
0
0
0
0
1
1
1
0
2
3
1
0
1
0
1
0
0
3
0
1
3
3
2
0
0
0
0
0
3
1
1
0
3
0
1
1
3
1
3
0
1
3
0
3
1
2
0
0
0
1
0
0
0
0
1
0
0
3
0
0
0
0
0
0
3
3
1
0
1
2
0
1
1
1
3
0
1
1
1
3
0
2
0
0
2
1
0
0
1
0
0
3
1
0
3
3
1
1
3
1
0
3
1
0
1
3
1
1
0
0
3
1
0
0
0
0
1
0
1
1
0
1
0
3
3
2
1
0
2
0
0
1
1
0
3
0
2
1
0
1
1
1
0
1
2
1
1
3
0
1
1
1
0
1
1
1
1
0
1
0
0
0
3
3
0
1
2
2
3
0
2
3
1
0
0
3
3
3
0
1
0
0
0
1
1
0
0
2
1
1
0
1
2
1
1
0
0
0
1
1
0
0
1
1
1
0
0
1
0
0
1
0
1
3
1
1
0
3
0
1
3
2
1
3
1
0
0
0
3
3
1
1
3
3
0
1
0
0
0
0
0
3
1
1
1
0
0
3
0
0
1
3
0
0
1
3
0
3
0
1
1
0
0
0
0
1
0
3
1
0
0
1
1
0
0
3
2
3
1
0
1
0
1
1
1
1
2
0
1
3
0
1
0
3
1
0
1
0
1
0
1
1
3
1
1
0
2
0
3
0
0
0
1
3
1
2
1
0
0
3
0
3
0
0
0
1
0
3
1
3
1
1
3
1
1
3
0
1
1
1
0
0
0
1
0
1
1
0
0
3
0
1
2
2
0
0
1
1
0
0
0
1
1
3
1
3
3
2
0
1
0
1
0
0
0
1
0
0
1
3
0
0
0
1
1
1
0
1
1
0
2
1
1
0
3
1
1
0
0
1
1
0
1
3
3
1
1
3
0
0
2


In [10]:
m.feed_forward(d.x)
djda = m.Optimizer.Loss.loss_derivative(m.layers[-1].a, d.y)

DEBUG:root:y:
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]
DEBUG:root:yhat:
[[ 0.09  0.57  0.22  0.12]
 [ 0.02  0.35  0.50  0.13]
 [ 0.06  0.67  0.14  0.14]
 ...
 [ 0.27  0.21  0.38  0.15]
 [ 0.29  0.31  0.15  0.25]
 [ 0.39  0.23  0.10  0.29]]
DEBUG:root:-y / yhat:
[[ 0.00  0.00 -4.59  0.00]
 [ 0.00  0.00  0.00 -7.53]
 [ 0.00  0.00 -7.34  0.00]
 ...
 [-3.74  0.00  0.00  0.00]
 [ 0.00 -3.19  0.00  0.00]
 [ 0.00 -4.33  0.00  0.00]]


In [11]:
l = m.layers[-1]
dadz = l.activation_derivative(l.z, l.a)
# print(f"{dadz.shape = }, {djda.shape = }")
# logging.debug(f"djda:\n {djda}\n")
djdz = np.einsum( 'ik,ikj->ij', djda, dadz)
djdz2 = l.a - d.y


array([[ 0.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00],
       ...,
       [ 0.00,  0.00,  0.00,  0.00],
       [ 0.00, -0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00]])

In [10]:
print(l.a)
print(d.y)
-1 / 0.22

[[ 0.09  0.57  0.22  0.12]
 [ 0.02  0.35  0.50  0.13]
 [ 0.06  0.67  0.14  0.14]
 ...
 [ 0.27  0.21  0.38  0.15]
 [ 0.29  0.31  0.15  0.25]
 [ 0.39  0.23  0.10  0.29]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]


-4.545454545454546