In [1]:
from Model import *
from dataset import Dataset
import numpy as np

In [2]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 4], activations = ["sigmoid"])
d.x = d.x.T
d.y = d.y.T

[4]


In [3]:
ex = d.x[:, 0][:, np.newaxis]
ex
ey = d.y[:, 0][:, np.newaxis]
ey

array([[0],
       [0],
       [1],
       [0]], dtype=uint8)

In [9]:
m.fit(d.x, d.y)

In [10]:
m.feed_forward(ex)

array([[ 1.00],
       [ 1.00],
       [ 1.00],
       [ 1.00]])

In [6]:
ex

array([[ 1.00],
       [-1.03],
       [ 0.88],
       [ 1.03],
       [ 0.37],
       [ 1.04],
       [ 0.36],
       [ 0.21]])