In [1]:
from Model import *
from dataset import Dataset
import numpy as np

In [2]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 4], activations = ["softmax"])
d.x = d.x.T
d.y = d.y.T

[4]


In [3]:
ex = d.x[:, 0][:, np.newaxis]
ex
ey = d.y[:, 0][:, np.newaxis]
ey

array([[0],
       [0],
       [1],
       [0]], dtype=uint8)

In [4]:
m.fit(d.x, d.y)

daondz shape:  (4, 1600, 1600)


In [11]:
# m.feed_forward(d.x)
l = m.layers[0]
dadz = m.layers[0].activation_derivative(m.layers[0].z, m.layers[0].a)
djda = m.Optimizer.Loss.loss_derivative(l.a, d.y)
djdz = np.einsum('ijk,ik->ij', dadz, djda)

In [19]:
m.Optimizer.Loss.loss_derivative(m.layers[-1].a, d.y)

array([[-0.00, -0.00, -0.00, ..., -15.51, -0.00, -0.00],
       [-0.00, -0.00, -0.00, ..., -0.00, -1.91, -2.10],
       [-6.45, -0.00, -4.89, ..., -0.00, -0.00, -0.00],
       [-0.00, -3.98, -0.00, ..., -0.00, -0.00, -0.00]])

In [21]:
1 / l.a

array([[ 2.36,  3.75,  2.12, ..., 15.51,  5.15,  4.62],
       [ 8.35,  2.65, 15.47, ...,  2.33,  1.91,  2.10],
       [ 6.45,  9.62,  4.89, ...,  3.70,  6.06,  6.42],
       [ 3.31,  3.98,  3.85, ...,  4.23,  8.42,  6.62]])

In [28]:
mask = np.random.choice(8, 3, replace=False)

In [29]:
mask

array([5, 6, 2])

In [32]:
a = [1,2,3,4,5,6,7,8]
a[mask]

TypeError: list indices must be integers or slices, not tuple

numpy.ndarray