In [2]:
from Model import *
from dataset import Dataset
import numpy as np

In [3]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 10, 4], activations = ["sigmoid", "softmax"])
l = m.layers[0]
d.x = d.x
d.y = d.y
ex = d.x[0][np.newaxis, :]
ey = d.y[0][np.newaxis, :]

In [4]:
m.fit(ex, ey)

Backwards : softmax_row
dadz.shape = (1, 4, 4), djda.shape = (1, 4)
OUT
self.local_gradient =array([[ 0.02,  0.16, -0.05, -0.07,  0.20, -0.10,  0.17,  0.08, -0.05,
         0.18]])
(11, 4)
Backwards : sigmoid
da sig
 [[ 0.24  0.25  0.25  0.25  0.25  0.22  0.24  0.24  0.22  0.22]]
da sig
 [[[ 0.24  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
  [ 0.00  0.25  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
  [ 0.00  0.00  0.25  0.00  0.00  0.00  0.00  0.00  0.00  0.00]
  [ 0.00  0.00  0.00  0.25  0.00  0.00  0.00  0.00  0.00  0.00]
  [ 0.00  0.00  0.00  0.00  0.25  0.00  0.00  0.00  0.00  0.00]
  [ 0.00  0.00  0.00  0.00  0.00  0.22  0.00  0.00  0.00  0.00]
  [ 0.00  0.00  0.00  0.00  0.00  0.00  0.24  0.00  0.00  0.00]
  [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.24  0.00  0.00]
  [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.22  0.00]
  [ 0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.22]]]
dadz.shape = (1, 10, 10), djda.shape = (1, 10)
OUT
self.local_gradien

In [5]:
for i in range(100):
    print(i, "\n\n")
    m.fit(d.x, d.y)

-0.00, ..., -0.00, -0.00, -0.00],
       [ 0.00, -0.00,  0.00, ...,  0.00, -0.00,  0.00],
       [ 0.00, -0.00, -0.00, ..., -0.00, -0.00,  0.00]])
(9, 10)
93 


Backwards : softmax_row
dadz.shape = (1600, 4, 4), djda.shape = (1600, 4)
OUT
self.local_gradient =array([[ 0.00,  0.00,  0.00, ...,  0.00, -0.00, -0.00],
       [ 0.00,  0.00,  0.00, ...,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00, ...,  0.00, -0.00, -0.00],
       ...,
       [ 0.00,  0.00,  0.00, ...,  0.00, -0.00,  0.00],
       [ 0.00, -0.00,  0.00, ..., -0.00,  0.00,  0.00],
       [ 0.00, -0.00,  0.00, ..., -0.00,  0.00,  0.00]])
(11, 4)
Backwards : sigmoid
da sig
 [[ 0.13  0.00  0.02 ...  0.01  0.00  0.01]
 [ 0.03  0.00  0.00 ...  0.00  0.00  0.00]
 [ 0.07  0.00  0.00 ...  0.00  0.00  0.00]
 ...
 [ 0.00  0.00  0.00 ...  0.00  0.00  0.02]
 [ 0.01  0.00  0.00 ...  0.09  0.20  0.07]
 [ 0.00  0.00  0.00 ...  0.01  0.00  0.23]]
da sig
 [[[ 0.13  0.00  0.00 ...  0.00  0.00  0.00]
  [ 0.00  0.00  0.00 ...  0.00  0.00  0

In [6]:
np.mean(m.layers[-1].a - d.y)

6.245004513516505e-19