In [1]:
import logging
logging.basicConfig(level=logging.DEBUG)


from Model import *
from dataset import Dataset
import numpy as np
from Optimizer import Optimizer
from Loss import *

logger = logging.getLogger('simple_example')
logger.setLevel(logging.DEBUG)

In [2]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 4], activations = ["softmax"], optimizer=Optimizer(learning_rate=0.1, Loss=CrossEntropyLoss()))
test = np.genfromtxt("../data/trainout.csv", delimiter=",")
l = m.layers[-1]
d.x = d.x
d.y = d.y
# d.y[0][2] = 0
# d.y[0][3] = 1
mask = [0,1]
ex = d.x[mask]
ey = d.y[mask]

In [3]:
# m.Optimizer.lr = 1
for i in range(1):
    m.fit(d.x, d.y)
    print("\n")
print(f"{l.z = }\n\n{l.a = }\n\n{d.y = }\n\n{l.x = }\n\n{l.w = }\n\n")


 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]]

DEBUG:root:djdz:
 [[  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 ...
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]]

DEBUG:root:djdw:
[[  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]]

DEBUG:root:next_djda.shape = (1600, 8) 
next_djda:  
[[  nan   nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 ...
 [  nan   nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]]


DEBUG:root:l.w :
[[  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   nan]
 [  nan   nan   nan   n

In [11]:
# for i in range(1):
#     m.fit(ex, ey)
#     print("\n")
# print(f"{l.a = }\n\n{d.y = }\n\n{l.x = }\n\n{l.w}\n\n")

In [5]:
np.mean(np.abs(m.layers[-1].a - d.y)) / 2

nan

In [17]:
errcount = 0
for yhat, y in zip(m.layers[-1].a, d.y):
    if (np.argmax(yhat) != np.argmax(y)):
        # print(yhat, y)
        errcount += 1
print(errcount)

50


In [18]:
c = 0
i = 0
for x, y in zip(m.layers[-1].a, test):
    # print(np.argmax(x), np.argmax(y))
    if (np.argmax(x) != np.argmax(y)):
        print(x, y)
        c += 1
print(c)

[ 0.00  1.00  0.00  0.00] [ 0.96  0.04  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.90  0.09  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.99  0.01  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.93  0.07  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.98  0.02  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.92  0.07  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.99  0.01  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.81  0.18  0.01  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.96  0.03  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.97  0.03  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.90  0.09  0.01  0.01]
[ 0.00  1.00  0.00  0.00] [ 0.99  0.01  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.84  0.15  0.00  0.01]
[ 0.00  1.00  0.00  0.00] [ 0.99  0.01  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.88  0.11  0.01  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.97  0.02  0.00  0.00]
[ 0.00  1.00  0.00  0.00] [ 0.99  0.01  0.00  0.00]
[ 0.00  0.00  1.00  0.00] [ 0.05  0.86  0.05  0.04]
[ 0.00  1.00  0.00  0.00] [ 0.94  0.06  0.00  0.00]
[ 0.00  1.00

In [10]:
m.feed_forward(d.x)
djda = m.Optimizer.Loss.loss_derivative(m.layers[-1].a, d.y)

DEBUG:root:y:
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]
DEBUG:root:yhat:
[[ 0.09  0.57  0.22  0.12]
 [ 0.02  0.35  0.50  0.13]
 [ 0.06  0.67  0.14  0.14]
 ...
 [ 0.27  0.21  0.38  0.15]
 [ 0.29  0.31  0.15  0.25]
 [ 0.39  0.23  0.10  0.29]]
DEBUG:root:-y / yhat:
[[ 0.00  0.00 -4.59  0.00]
 [ 0.00  0.00  0.00 -7.53]
 [ 0.00  0.00 -7.34  0.00]
 ...
 [-3.74  0.00  0.00  0.00]
 [ 0.00 -3.19  0.00  0.00]
 [ 0.00 -4.33  0.00  0.00]]


In [11]:
l = m.layers[-1]
dadz = l.activation_derivative(l.z, l.a)
# print(f"{dadz.shape = }, {djda.shape = }")
# logging.debug(f"djda:\n {djda}\n")
djdz = np.einsum( 'ik,ikj->ij', djda, dadz)
djdz2 = l.a - d.y


array([[ 0.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00],
       ...,
       [ 0.00,  0.00,  0.00,  0.00],
       [ 0.00, -0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00]])

In [10]:
print(l.a)
print(d.y)
-1 / 0.22

[[ 0.09  0.57  0.22  0.12]
 [ 0.02  0.35  0.50  0.13]
 [ 0.06  0.67  0.14  0.14]
 ...
 [ 0.27  0.21  0.38  0.15]
 [ 0.29  0.31  0.15  0.25]
 [ 0.39  0.23  0.10  0.29]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]


-4.545454545454546