In [1]:
import logging
logging.basicConfig(level=logging.DEBUG)


from Model import *
from dataset import Dataset
import numpy as np
from Optimizer import Optimizer
from Loss import *
from Layer import backproplogger

backproplogger.setLevel(logging.WARNING)

# logger = logging.getLogger('simple_example')
# logger.setLevel(logging.DEBUG)

In [30]:
def count_errors(yhati, yi):
    errcount = 0
    for yhat, y in zip(yhati, yi):
        if (np.argmax(yhat) != np.argmax(y)):
            errcount += 1
    return(errcount)

In [68]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 10, 4], activations = ["sigmoid", "softmax"], optimizer=Optimizer(learning_rate=0.001, Loss=CrossEntropyLoss()))
test = np.genfromtxt("../data/trainout.csv", delimiter=",")
l = m.layers[-1]
d.x = d.x
d.y = d.y
d.y[0][2] = 0
d.y[0][0] = 1
mask = []
for i in range(100):
    mask.append(i)
ex = d.x[mask]
ey = d.y[mask]

In [70]:
# m.Optimizer.lr = 1
x = ex
y = ey
for i in range(100):
    m.fit(x, y)
    # print("\n")
print(f"l.z:\n{l.z}\n\nl.a:\n{l.a}\n\ny:\n{y}\n\nx:\n{x}\n\nl.w:\n{l.w}\n\n")
print(count_errors(l.a, y))

l.z:
[[-1.40 -1.70  3.56 -0.44]
 [-2.19 -1.20 -0.80  4.52]
 [-1.64 -1.62  3.91 -0.57]
 ...
 [ 4.22 -1.37 -0.60 -2.40]
 [-1.40  4.43 -1.35 -0.67]
 [-0.64  4.35 -1.18 -1.58]]

l.a:
[[ 0.01  0.01  0.97  0.02]
 [ 0.00  0.00  0.00  0.99]
 [ 0.00  0.00  0.98  0.01]
 ...
 [ 0.99  0.00  0.01  0.00]
 [ 0.00  0.99  0.00  0.01]
 [ 0.01  0.99  0.00  0.00]]

y:
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]

x:
[[ 1.00 -1.03  0.88 ...  1.04  0.36  0.21]
 [ 1.00 -1.16 -1.39 ... -0.54 -1.21  0.65]
 [ 1.00 -0.80  1.26 ...  1.86  1.02  1.32]
 ...
 [ 1.00  0.97 -0.85 ... -0.32  1.33 -1.75]
 [ 1.00  0.79  0.44 ... -1.25 -1.06  1.32]
 [ 1.00  1.25  0.82 ... -0.01 -1.48  0.10]]

l.w:
[[ 0.50 -0.40 -0.08 -0.21]
 [-0.89  1.25  1.58 -2.02]
 [ 0.39 -2.35  0.73  1.23]
 [ 1.52  0.97 -1.47 -0.81]
 [ 0.09 -1.44  1.70 -0.36]
 [ 1.20 -0.89 -0.26 -0.65]
 [-1.57  0.24  0.45  1.04]
 [-1.98  0.82 -0.14  1.33]
 [-0.29  1.55 -0.10 -0.60]
 [ 1.23  0.20 -0.13 -1.01]
 [ 0.10  0.48 -1.79  1.55]]


30


In [37]:
np.mean(np.abs(m.layers[-1].a - d.y)) / 2

0.05658387756474216

In [10]:
m.layers[0].a

array([[ 1.00,  0.00,  0.00, ...,  0.09,  0.00,  0.00],
       [ 0.00,  1.00,  0.00, ...,  1.00,  0.00,  1.00],
       [ 1.00,  0.00,  0.00, ...,  0.23,  0.00,  0.00],
       ...,
       [ 0.00,  1.00,  1.00, ...,  0.00,  1.00,  0.00],
       [ 1.00,  0.00,  1.00, ...,  1.00,  1.00,  1.00],
       [ 1.00,  0.00,  1.00, ...,  0.99,  1.00,  1.00]])

In [39]:
c = 0
i = 0
for x, y in zip(m.feed_forward(d.x), d.y):
    if (np.argmax(x) != np.argmax(y)):
        print(x, y)
        c += 1
print(c)

[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 0.96  0.00  0.04  0.00] [0 0 1 0]
[ 0.05  0.68  0.26  0.01] [1 0 0 0]
[ 0.99  0.00  0.01  0.00] [0 0 1 0]
[ 0.54  0.00  0.46  0.00] [0 0 1 0]
[ 0.97  0.00  0.02  0.00] [0 0 1 0]
[ 0.99  0.00  0.01  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 0.54  0.00  0.46  0.00] [0 0 1 0]
[ 0.87  0.00  0.13  0.00] [0 0 1 0]
[ 0.90  0.00  0.10  0.00] [0 0 1 0]
[ 0.99  0.00  0.01  0.00] [0 0 1 0]
[ 0.75  0.00  0.25  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 0.98  0.00  0.02  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 0.99  0.00  0.01  0.00] [0 0 1 0]
[ 0.98  0.00  0.02  0.00] [0 0 1 0]
[ 0.56  0.01  0.00  0.44] [0 0 0 1]
[ 0.90  0.00  0.10  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 0.97  0.00  0.03  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 0.93  0.00  0.07  0.00] [0 0 1 0]
[ 0.70  0.00  0.29  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0

In [35]:
m.feed_forward(d.x)

array([[ 1.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  1.00],
       [ 0.00,  0.00,  1.00,  0.00],
       ...,
       [ 1.00,  0.00,  0.00,  0.00],
       [ 0.00,  1.00,  0.00,  0.00],
       [ 0.00,  1.00,  0.00,  0.00]])

In [40]:
for x in m.feed_forward(d.x):
    print(np.argmax(x))

0
3
2
0
0
3
0
1
0
1
1
1
1
3
2
2
0
0
2
1
0
0
2
1
0
1
3
1
0
1
1
0
2
1
0
0
1
1
3
1
0
1
0
1
1
0
0
1
3
0
0
3
3
0
0
3
1
3
1
0
3
2
1
1
1
1
1
0
0
1
2
3
3
1
2
1
0
0
1
1
1
3
3
0
1
1
1
1
1
0
0
0
0
1
1
1
0
2
3
1
0
1
0
1
0
0
3
0
1
3
3
2
0
0
0
0
0
3
1
1
0
3
0
1
1
3
1
3
0
1
3
0
3
1
2
0
0
0
1
0
0
0
0
1
0
0
3
0
0
0
0
0
0
3
3
1
0
1
2
0
1
1
1
3
0
1
1
1
3
0
2
0
0
2
1
0
0
1
0
0
3
1
0
3
3
1
1
3
1
0
3
1
0
1
3
1
1
0
0
3
1
0
0
0
0
1
0
1
1
0
1
0
3
3
2
1
0
2
0
0
1
1
0
3
0
2
1
0
1
1
1
0
1
2
1
1
3
0
1
1
1
0
1
1
1
1
0
1
0
0
0
3
3
0
1
2
2
3
0
2
3
1
0
0
3
3
3
0
1
0
0
0
1
1
0
0
2
1
1
0
1
2
1
1
0
0
0
1
1
0
0
1
1
1
0
0
1
0
0
1
0
1
3
1
1
0
3
0
1
3
2
1
3
1
0
0
0
3
3
1
1
3
3
0
1
0
0
0
0
0
3
1
1
1
0
0
3
0
0
1
3
0
0
1
3
0
3
0
1
1
0
0
0
0
1
0
3
1
0
0
1
1
0
0
3
2
3
1
0
1
0
1
1
1
1
2
0
1
3
0
1
0
3
1
0
1
0
1
0
1
1
3
1
1
0
2
0
3
0
0
0
1
3
1
2
1
0
0
3
0
3
0
0
0
1
0
3
1
3
1
1
3
1
1
3
0
1
1
1
0
0
0
1
0
1
1
0
0
3
0
1
2
2
0
0
1
1
0
0
0
1
1
3
1
3
3
2
0
1
0
1
0
0
0
1
0
0
1
3
0
0
0
1
1
1
0
1
1
0
2
1
1
0
3
1
1
0
0
1
1
0
1
3
3
1
1
3
0
0
2


In [10]:
m.feed_forward(d.x)
djda = m.Optimizer.Loss.loss_derivative(m.layers[-1].a, d.y)

DEBUG:root:y:
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]
DEBUG:root:yhat:
[[ 0.09  0.57  0.22  0.12]
 [ 0.02  0.35  0.50  0.13]
 [ 0.06  0.67  0.14  0.14]
 ...
 [ 0.27  0.21  0.38  0.15]
 [ 0.29  0.31  0.15  0.25]
 [ 0.39  0.23  0.10  0.29]]
DEBUG:root:-y / yhat:
[[ 0.00  0.00 -4.59  0.00]
 [ 0.00  0.00  0.00 -7.53]
 [ 0.00  0.00 -7.34  0.00]
 ...
 [-3.74  0.00  0.00  0.00]
 [ 0.00 -3.19  0.00  0.00]
 [ 0.00 -4.33  0.00  0.00]]


In [11]:
l = m.layers[-1]
dadz = l.activation_derivative(l.z, l.a)
# print(f"{dadz.shape = }, {djda.shape = }")
# logging.debug(f"djda:\n {djda}\n")
djdz = np.einsum( 'ik,ikj->ij', djda, dadz)
djdz2 = l.a - d.y


array([[ 0.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00],
       ...,
       [ 0.00,  0.00,  0.00,  0.00],
       [ 0.00, -0.00,  0.00,  0.00],
       [ 0.00,  0.00,  0.00,  0.00]])

In [10]:
print(l.a)
print(d.y)
-1 / 0.22

[[ 0.09  0.57  0.22  0.12]
 [ 0.02  0.35  0.50  0.13]
 [ 0.06  0.67  0.14  0.14]
 ...
 [ 0.27  0.21  0.38  0.15]
 [ 0.29  0.31  0.15  0.25]
 [ 0.39  0.23  0.10  0.29]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]


-4.545454545454546