In [4]:
from Model import *
from dataset import Dataset
import numpy as np
from Optimizer import Optimizer
from Loss import *

In [6]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 4], activations = ["softmax"], optimizer=Optimizer(learning_rate=0.1, Loss=CrossEntropyLoss()))
l = m.layers[0]
d.x = d.x
d.y = d.y
mask = [0,1]
ex = d.x[mask]
ey = d.y[mask]
ex

array([[ 1.00, -1.03,  0.88,  1.03,  0.37,  1.04,  0.36,  0.21],
       [ 1.00, -1.16, -1.39,  1.15, -2.14, -0.54, -1.21,  0.65]])

In [7]:
for i in range(10000):
    m.fit(d.x, d.y)
print(f"{l.a = }\n\n{d.y = }\n\n{l.x = }\n\n{l.w}\n\n")

TypeError: 'int' object is not callable

In [8]:


# d.y[-1][1] = 0
# d.y[-1][2] = 1

# for i in range(10):
#     # print(i, "\n\n")
#     m.fit(d.x, d.y)

In [14]:
np.mean(np.abs(m.layers[-1].a - d.y))

0.008942403190105086

In [15]:
for yhat, y in zip(m.layers[-1].a, d.y):
    if (np.argmax(yhat) != np.argmax(y)):
        print(yhat, y)

[ 0.00  0.00  0.00  1.00] [0 0 1 0]
[ 0.00  1.00  0.00  0.00] [0 0 1 0]
[ 0.00  0.00  1.00  0.00] [0 0 0 1]
[ 0.00  1.00  0.00  0.00] [0 0 1 0]
[ 0.00  1.00  0.00  0.00] [0 0 1 0]
[ 0.00  0.00  1.00  0.00] [0 0 0 1]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 0.00  0.00  1.00  0.00] [1 0 0 0]
[ 0.00  0.00  1.00  0.00] [1 0 0 0]
[ 0.00  0.00  0.00  1.00] [0 0 1 0]
[ 0.00  0.00  1.00  0.00] [1 0 0 0]
[ 0.00  0.00  1.00  0.00] [0 1 0 0]
[ 0.97  1.00  0.00  0.00] [1 0 0 0]
[ 0.00  1.00  0.00  0.00] [0 0 0 1]
[ 0.00  1.00  0.00  0.00] [1 0 0 0]
[ 0.00  0.00  0.00  1.00] [0 1 0 0]
[ 0.00  1.00  0.00  0.00] [0 0 0 1]
[ 1.00  0.00  0.00  0.00] [0 0 1 0]
[ 1.00  0.00  0.00  0.00] [0 1 0 0]
[ 1.00  0.00  0.00  0.00] [0 1 0 0]
[ 0.00  0.00  1.00  0.00] [0 0 0 1]
[ 0.00  0.00  1.00  0.00] [0 0 0 1]
[ 0.00  1.00  0.00  0.00] [0 0 1 0]
[ 0.00  0.00  1.00  0.00] [0 0 0 1]
[ 0.00  1.00  0.00  0.00] [1 0 0 0]
[ 0.00  0.00  1.00  0.00] [1 0 0 0]
[ 0.00  0.00  1.00  0.00] [1 0 0 0]
[ 0.00  1.00  0.00  0.00] [1