In [1]:
import logging
logging.basicConfig(level=logging.DEBUG)


from Model import *
from dataset import Dataset
import numpy as np
from Optimizer import Optimizer
from Loss import *

logger = logging.getLogger('simple_example')
logger.setLevel(logging.DEBUG)

In [2]:
d = Dataset("../datasets/dataset_train.csv")
m = Model(sizes = [8, 4], activations = ["softmax"], optimizer=Optimizer(learning_rate=0.01, Loss=CrossEntropyLoss()))
test = np.genfromtxt("../data/trainout.csv", delimiter=",")
l = m.layers[-1]
d.x = d.x
d.y = d.y
d.y[0][2] = 0
d.y[0][1] = 1
mask = [0,1]
ex = d.x[mask]
ey = d.y[mask]

In [4]:
for i in range(1):
    m.fit(d.x, d.y)
    print("\n")
print(f"{l.z = }\n\n{l.a = }\n\n{d.y = }\n\n{l.x = }\n\n{l.w = }\n\n")

DEBUG:root:z:
[[-3970.32  0.00 -8439.77 -4992.57]
 [-1366.52 -154.25  0.00 -4921.61]
 [-4325.64  0.00 -11833.21 -5560.85]
 ...
 [-5943.06 -3807.83  0.00 -1589.33]
 [ 0.00 -6629.85 -411.94 -366.38]
 [-779.33 -7072.59 -850.96  0.00]]

DEBUG:root:e:
[[ 0.00  1.00  0.00  0.00]
 [ 0.00  0.00  1.00  0.00]
 [ 0.00  1.00  0.00  0.00]
 ...
 [ 0.00  0.00  1.00  0.00]
 [ 1.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  1.00]]
DEBUG:root:s : [[ 1.00]
 [ 1.00]
 [ 1.00]
 ...
 [ 1.00]
 [ 1.00]
 [ 1.00]]
DEBUG:root:Backwards : softmax_row
DEBUG:root:djda:
 [[ 0.00 -0.00  0.00  0.00]
 [ 0.00  0.00 -625.00 625.00]
 [ 0.00 -625.00 625.00  0.00]
 ...
 [625.00  0.00 -625.00  0.00]
 [-625.00 625.00  0.00  0.00]
 [ 0.00 625.00  0.00 -625.00]]

DEBUG:root:djdz:
 [[ 0.00  0.00  0.00  0.00]
 [ 0.00  0.00 -0.00  0.00]
 [ 0.00  0.00  0.00  0.00]
 ...
 [ 0.00  0.00  0.00  0.00]
 [-0.00  0.00  0.00  0.00]
 [ 0.00  0.00  0.00  0.00]]

DEBUG:root:djdw:
[[111.88 -29.99 -65.44 -16.45]
 [111.88 -29.99 -65.44 -16.45]
 [99.39

In [7]:
for i in range(1):
    m.fit(ex, ey)
    print("\n")
print(f"{l.a = }\n\n{d.y = }\n\n{l.x = }\n\n{l.w}\n\n")

DEBUG:root:s : [[1.2082]
 [2.0132]]
DEBUG:root:Backwards : softmax_row
DEBUG:root:djda:
 [[-91488.0224 432367.6323 -217960.3425 -122917.2675]
 [-24094.5045 -346474.1062 -496713.2603 867283.8710]]

DEBUG:root:djdz:
 [[-24329.4551 146408.0214 -85527.9833 -36550.5830]
 [5497.4433 -32647.3239 -121429.7705 148579.6511]]

DEBUG:root:djdw:
[[-18832.0118 113760.6975 -206957.7538 112029.0682]
 [-18832.0118 113760.6975 -206957.7538 112029.0682]
 [18741.8381 -113285.8576 228590.1365 -134046.1170]
 [-28961.7365 173680.8213 93400.0510 -238119.1358]
 [-18659.7807 112790.0150 -227640.1032 133509.8689]
 [-20846.9292 124519.8490 228200.7393 -331873.6591]
 [-28249.3246 169763.3978 -23771.8659 -117742.2073]
 [-15310.9172 91610.7573 116512.3234 -192812.1635]
 [-1625.5303 10065.7805 -97584.1046 89143.8545]]

DEBUG:root:next_djda.shape = (2, 8) 
next_djda:  
[[395268.6818 -350876.7866 584285.8509 -98562.7953 -221810.3341
  145887.8257 199568.9161 331633.0406]
 [-949802.5171 398579.6444 385518.3915 -581288.3

In [5]:
np.mean(np.abs(m.layers[-1].a - d.y)) / 2

0.4971875000000027

In [15]:
errcount = 0
for yhat, y in zip(m.layers[-1].a, d.y):
    if (np.argmax(yhat) != 1):
        # print(yhat, y)
        errcount += 1
print(errcount)

0


In [10]:
ey

array([[0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=uint8)

In [13]:
for x, y in zip(m.layers[-1].a, test):
    print(np.argmax(x), np.argmax(y))
    if (np.argmax(x) != np.argmax(y)):
        print(x, y)

2 2
3 3
2 2
0 0
0 0
3 3
0 0
1 1
0 0
1 1
1 1
1 1
1 1
3 3
2 2
2 2
0 0
0 0
2 2
1 1
0 0
0 0
2 2
1 1
2 2
1 1
3 3
1 1
0 0
1 1
1 1
0 0
2 2
1 1
2 2
2 2
1 1
1 1
3 3
0 0
0 0
1 1
2 2
1 1
1 1
2 2
2 2
1 1
3 3
0 0
0 0
3 3
3 3
2 2
0 0
3 3
1 1
3 3
1 1
0 0
3 3
2 2
1 1
1 1
1 1
1 1
1 1
2 2
0 0
1 1
2 2
3 3
3 3
1 1
2 2
1 1
2 2
2 2
1 1
1 1
1 1
3 3
3 3
0 0
1 1
1 1
1 1
1 1
1 1
0 0
0 0
0 0
2 2
1 1
1 1
1 1
0 0
2 2
3 3
1 1
0 0
1 1
2 2
1 1
2 2
0 0
3 3
0 0
1 1
3 3
3 3
2 2
2 2
2 2
2 2
0 0
2 2
3 3
1 1
1 1
2 2
3 3
2 2
1 1
1 1
3 3
1 1
3 3
3 3
1 1
3 3
0 0
3 3
1 1
2 2
2 2
2 2
2 2
1 1
0 0
0 0
2 2
0 0
1 1
0 0
0 0
3 3
0 0
0 0
0 0
2 2
0 0
0 0
3 3
3 3
1 1
0 0
1 1
2 2
2 2
1 1
1 1
1 1
3 3
2 2
1 1
1 1
1 1
3 3
0 0
2 2
0 0
0 0
2 2
1 1
0 0
2 2
1 1
2 2
2 2
3 3
1 1
2 2
3 3
3 3
1 1
1 1
3 3
1 1
0 0
3 3
1 1
2 2
1 1
3 3
1 1
1 1
2 2
0 0
3 3
1 1
0 0
2 2
2 2
0 0
1 1
0 0
1 1
1 1
2 2
1 1
0 0
3 3
3 3
2 2
1 1
0 0
2 2
0 0
0 0
1 1
1 1
0 0
3 3
0 0
2 2
1 1
0 0
1 1
1 1
1 1
0 0
1 1
2 2
1 1
1 1
3 3
2 2
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
0 0
2 2


array([[-0.04, -0.04,  0.12, -0.04],
       [-0.00, -0.00, -0.00,  0.00],
       [-0.01, -0.01,  0.03, -0.01],
       ...,
       [ 0.00, -0.00, -0.00, -0.00],
       [-0.00,  0.00, -0.00, -0.00],
       [-0.00,  0.00, -0.00, -0.00]])